baseurl: /
permalink: /news/:year-:month-:day-:title.html
paginate: 5
paginate_path: "/news/page:num"
exclude:
  - Guardfile
  - "sandstorm.io.*"
  - README.md
  - "*.sh"
gems:
  - octopress-autoprefixer
  - jekyll-paginate
